Repository CorrM/Unreal-Finder-Tool, pull requests merged in 2019-06, with the labels that each got.

#8 Support GObjects Chunks
  README.md
  UnrealFinderTool/ClassFinder.cpp
  UnrealFinderTool/ImControl.h
  UnrealFinderTool/SdkGen/Engine/ObjectsStore.cpp
  UnrealFinderTool/SdkGen/Engine/ObjectsStore.h
  UnrealFinderTool/SdkGenerator.cpp
  UnrealFinderTool/UnrealFinderTool.cpp
  UnrealFinderTool/Utils.cpp
Labels: enhancement

#14 Added fixes for lagging UI when generating
  UnrealFinderTool/UnrealFinderTool.cpp
  UnrealFinderTool/UnrealFinderTool.vcxproj
Labels: possible bug

#16 Fixed a number of UI bugs
  UnrealFinderTool/SdkGenerator.cpp
  UnrealFinderTool/UiWindow.cpp
  UnrealFinderTool/UiWindow.h
  UnrealFinderTool/UnrealFinderTool.cpp
  UnrealFinderTool/UnrealFinderTool.vcxproj
  UnrealFinderTool/Utils.cpp
Labels: bug

#17 Added new GNames autodetection code
  UnrealFinderTool/UnrealFinderTool.cpp
Labels: enhancement

#19 Debugging
  .gitignore
  UnrealFinderTool/Debug.cpp
  UnrealFinderTool/Debug.h
  UnrealFinderTool/ImControl.h
  UnrealFinderTool/Logger.cpp
  UnrealFinderTool/Logger.h
  UnrealFinderTool/UiWindow.cpp
  UnrealFinderTool/UnrealFinderTool.cpp
  UnrealFinderTool/Utils.cpp
  UnrealFinderTool/Utils.h
  UnrealFinderTool/pch.h
Labels: bug, enhancement

#21 Re-wrote autoscan method
  UnrealFinderTool/UnrealFinderTool.cpp
  UnrealFinderTool/UnrealFinderTool.vcxproj
  UnrealFinderTool/UnrealFinderTool.vcxproj.filters
Labels: enhancement

#20 EngineJson and Hard Core changes
  UnrealFinderTool/Config/Core/CoreStructs.json
  UnrealFinderTool/Config/Core/GNames.json
  UnrealFinderTool/Config/Core/GObjects.json
  UnrealFinderTool/Config/EngineCore/EngineBase.json
  UnrealFinderTool/Config/EngineCore/[Override example] Engine-4.0.0.json
  UnrealFinderTool/Debug.cpp
  UnrealFinderTool/ImControl.h
  UnrealFinderTool/InstanceLogger.cpp
  UnrealFinderTool/InstanceLogger.h
  UnrealFinderTool/JsonReflector.cpp
  UnrealFinderTool/JsonReflector.h
  UnrealFinderTool/JsonTypes.rar
  UnrealFinderTool/Memory.cpp
  UnrealFinderTool/Memory.h
  UnrealFinderTool/PatternScan.cpp
  UnrealFinderTool/SdkGen/Engine/NamesStore.cpp
  UnrealFinderTool/SdkGen/Engine/NamesStore.h
  UnrealFinderTool/SdkGen/Engine/ObjectsStore.cpp
  UnrealFinderTool/SdkGen/Engine/ObjectsStore.h
  UnrealFinderTool/SdkGen/Engine/Package.cpp
  UnrealFinderTool/SdkGen/Engine/Package.h
  UnrealFinderTool/SdkGen/Engine/UE4/GenericTypes.cpp
  UnrealFinderTool/SdkGen/Engine/UE4/GenericTypes.h
  UnrealFinderTool/SdkGen/EngineClasses.h
  UnrealFinderTool/SdkGenerator.cpp
  UnrealFinderTool/UnrealFinderTool.cpp
  UnrealFinderTool/UnrealFinderTool.vcxproj
  UnrealFinderTool/UnrealFinderTool.vcxproj.filters
  UnrealFinderTool/Utils.cpp
  UnrealFinderTool/Utils.h
Labels: enhancement

#23 Various fixes
  UnrealFinderTool/Scanner.cpp
  UnrealFinderTool/Scanner.h
  UnrealFinderTool/UnrealFinderTool.cpp
  UnrealFinderTool/Utils.cpp
Labels: bug, enhancement

#24 New UI & all functions now faster
  UnrealFinderTool/GObjectsFinder.cpp
  UnrealFinderTool/GObjectsFinder.h
  UnrealFinderTool/GnamesFinder.cpp
  UnrealFinderTool/ImControl.h
  UnrealFinderTool/Memory.cpp
  UnrealFinderTool/Memory.h
  UnrealFinderTool/MemoryEditor.h
  UnrealFinderTool/ParallelWorker.h
  UnrealFinderTool/PatternScan.cpp
  UnrealFinderTool/PatternScan.h
  UnrealFinderTool/Scanner.cpp
  UnrealFinderTool/Scanner.h
  UnrealFinderTool/SdkGenerator.cpp
  UnrealFinderTool/UiWindow.cpp
  UnrealFinderTool/UiWindow.h
  UnrealFinderTool/UnrealFinderTool.cpp
  UnrealFinderTool/UnrealFinderTool.vcxproj
  UnrealFinderTool/UnrealFinderTool.vcxproj.filters
  UnrealFinderTool/Utils.cpp
  UnrealFinderTool/Utils.h
Labels: enhancement, possible bug

#28 Solve different Engine Support
  UnrealFinderTool/Config/EngineCore/EngineBase.json
  UnrealFinderTool/SdkGen/EngineClasses.h
Labels: bug

#32 Fix x32 games on x64 version of tool & Improve Parallel Worker
  .gitignore
  UnrealFinderTool/GObjectsFinder.cpp
  UnrealFinderTool/ImControl.h
  UnrealFinderTool/JsonReflector.cpp
  UnrealFinderTool/JsonReflector.h
  UnrealFinderTool/ParallelWorker.h
  UnrealFinderTool/SdkGen/EngineClasses.h
  UnrealFinderTool/UnrealFinderTool.cpp
  UnrealFinderTool/Utils.h
Labels: bug

#39 Fixed CoreUObject being dumped twice and overridden with empty data.
  UnrealFinderTool/SdkGenerator.cpp
Labels: bug
